language: python

python:
  - "2.7"

install:
- pip install tox-travis

script:
  - tox -e travis
  - coverage run --source eight_bit_computer -m pytest
  - coverage report -m

after_success:
  - coveralls